### ISSUE TITLE
System prompt and API keys suddenly not saved anymore

### ISSUE THREAD

**Issue by Arche151** [cogentapps/chat-with-gpt#124]
I don't know why, but even though it worked fine yesterday, today when starting the self-hosted version of Chat with GPT, my API keys and custom system prompt were gone :(

**Comment by cogentapps** [comment]
Are you running the latest version? There was a bug related to this, but it should be fixed: https://github.com/cogentapps/chat-with-gpt/issues/103

System prompt and API keys are stored in your browser's local storage by default (unless you configure the API key in a config file on the server). Local storage is deleted when you clear history/cache/website data, but should persist otherwise.
