### ISSUE TITLE
Question about auth0

### ISSUE THREAD

**Issue by Seanmclem** [cogentapps/chat-with-gpt#14]
The example uses auth0 for login. Can there be an example in the readme regarding 

- what this is for
- how It might be replaced if we self-host/local?

**Comment by cogentapps** [comment]
The server-side code for self-hosting should be up in the next few days, and will include other options for authentication.

**Comment by Seanmclem** [comment]
> The server-side code for self-hosting should be up in the next few days, and will include other options for authentication.

Cool thanks, but what is the additional authentication for? Like, saving chat history or something else.

**Comment by cogentapps** [comment]
Right now login is for saving and syncing your chat history between devices. If you don’t need that, it isn’t required. For self-hosting, you can just deploy the web app without a server and it will work fine (except for the “share chat” button, which needs a database).

Future versions of the self-hosted server will also add (optional) support for running API calls on your server instead of in the browser, using an API key from an environmental variable, which some people might prefer.

**Comment by Seanmclem** [comment]
> Right now login is for saving and syncing your chat history between devices. If you don’t need that, it isn’t required. For self-hosting, you can just deploy the web app without a server and it will work fine (except for the “share chat” button, which needs a database).
> 
> 
> 
> Future versions of the self-hosted server will also add (optional) support for running API calls on your server instead of in the browser, using an API key from an environmental variable, which some people might prefer.

Nice. Is there a database where they'd by synced? I set up my own? Or something else already configured

**Comment by cogentapps** [comment]
I added the server code for reference - still working on better documentation.

It uses a SQLite database by default.
