### ISSUE TITLE
[Bug] Listing number with code blocks always starts with 1

### ISSUE THREAD

**Issue by LaChimere** [cogentapps/chat-with-gpt#47]
When letting it answer many code blocks, the listing number is always 1 as below:

![image](https://user-images.githubusercontent.com/48675121/226080460-db5784b1-8a8c-42c9-872b-54832ad9f3ad.png)

**Comment by Nishad-007** [comment]
could you provide the code behind this render , this will help to solve the issue

**Comment by LaChimere** [comment]
> could you provide the code behind this render , this will help to solve the issue

I'm not really familiar with React but I suppose `app\src\components\markdown.tsx` might give some hints.

**Comment by cogentapps** [comment]
Fixed by https://github.com/cogentapps/chat-with-gpt/commit/216ecd5b32da3d0c1ca4746b5d826db36c66ae36 - will roll out in the next few days.

Basically, the code blocks are causing the markdown renderer (react-markdown) to treat each list item as a separate list and generate separate `<ol>` elements, which resets the number. This fix makes it use the correct number.

**Comment by LaChimere** [comment]
> Fixed by [216ecd5](https://github.com/cogentapps/chat-with-gpt/commit/216ecd5b32da3d0c1ca4746b5d826db36c66ae36) - will roll out in the next few days.
> 
> Basically, the code blocks are causing the markdown renderer (react-markdown) to treat each list item as a separate list and generate separate `<ol>` elements, which resets the number. This fix makes it use the correct number.

Cool, thanks. This issue will be closed.
